data:extend({
	{
		type = "recipe",
		name = "pelagos-biochamber",
		category = "organic-or-assembling",
		icon = "__TS_Pelagos_CF__/graphics/pelagos-biochamber.png",
		surface_conditions = {
			{
				property = "pressure",
				min = 1809,
				max = 1809,
			},
		},
		energy_required = 20,
		ingredients = {
			{ type = "item", name = "nutrients", amount = 5 },
			{ type = "item", name = "fermentation-bacteria", amount = 1 },
			{ type = "item", name = "iron-plate", amount = 25 },
			{ type = "item", name = "landfill", amount = 1 },
		},
		results = { { type = "item", name = "biochamber", amount = 1 } },
		auto_recycle = false,
		enabled = false,
	},
	{
		type = "recipe",
		name = "pelagos-bioplastic",
		icon = "__TS_Pelagos_CF__/graphics/pelagos-plastic-bar.png",
		category = "organic",
		subgroup = "agriculture-products",
		order = "a[organic-products]-c[pelagos-bioplastic]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 2,
		ingredients = {
			{ type = "fluid", name = "ethanol", amount = 40 },
			{ type = "fluid", name = "methane", amount = 60 },
		},
		results = {
			{ type = "item", name = "plastic-bar", amount = 3 },
		},
		crafting_machine_tint = {
			primary = { r = 1.0, g = 1.0, b = 1.0, a = 1.000 },
			secondary = { r = 0.9, g = 1.0, b = 0.8, a = 1.000 },
			tertiary = { r = 1.0, g = 1.0, b = 1.0, a = 1.000 },
			quaternary = { r = 0.9, g = 1.0, b = 0.8, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "pelagos-biolubricant",
		icon = "__TS_Pelagos_CF__/graphics/pelagos-lubricant.png",
		icons = {
			{ icon = "__TS_Pelagos_CF__/graphics/coconut-oil.png", icon_size = 64 },
			{ icon = "__base__/graphics/icons/fluid/lubricant.png", icon_size = 64, shift = { 0, 16 } },
			--{ icon = "__base__/graphics/icons/fluid/lubricant.png", icon_size = 64, scale = 0.5, shift = { 12, 12 } },
		},
		category = "organic",
		subgroup = "agriculture-products",
		order = "a[organic-products]-c[pelagos-biolubricant]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		ingredients = {
			{ type = "fluid", name = "coconut-oil", amount = 20 },
			{ type = "item", name = "activated-carbon", amount = 1 },
		},
		results = {
			{ type = "fluid", name = "lubricant", amount = 25 },
			{ type = "item", name = "spoilage", amount = 1 },
		},
		main_product = "lubricant",
		crafting_machine_tint = {
			primary = { r = 0.22, g = 0.64, b = 0.11, a = 1.000 },
			secondary = { r = 0.2, g = 0.22, b = 0.1, a = 1.000 },
			tertiary = { r = 0.22, g = 0.64, b = 0.11, a = 1.000 },
			quaternary = { r = 0.2, g = 0.22, b = 0.1, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "pelagos-processing-unit",
		icon = "__TS_Pelagos_CF__/graphics/pelagos-processing-unit.png",
		category = "electronics-with-fluid",
		order = "b[circuits]-d[pelagos-processing-unit]",
		enabled = false,
		auto_recycle = false,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "electronic-circuit", amount = 20 },
			{ type = "item", name = "advanced-circuit", amount = 2 },
			{ type = "fluid", name = "ethanol", amount = 5 },
		},
		results = { { type = "item", name = "processing-unit", amount = 1 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "pelagos-battery",
		icon = "__TS_Pelagos_CF__/graphics/pelagos-battery.png",
		category = "chemistry-or-cryogenics",
		energy_required = 4,
		enabled = false,
		ingredients = {
			{ type = "fluid", name = "ethanol", amount = 20 },
			{ type = "item", name = "iron-plate", amount = 1 },
			{ type = "item", name = "activated-carbon", amount = 1 },
		},
		results = { { type = "item", name = "battery", amount = 2 } },
		crafting_machine_tint = {
			primary = { r = 0.965, g = 0.482, b = 0.338, a = 1.000 }, -- #f67a56ff
			secondary = { r = 0.831, g = 0.560, b = 0.222, a = 1.000 }, -- #d38e38ff
			tertiary = { r = 0.728, g = 0.818, b = 0.443, a = 1.000 }, -- #b9d070ff
			quaternary = { r = 0.939, g = 0.763, b = 0.191, a = 1.000 }, -- #efc230ff
		},
		allow_productivity = true,
		auto_recycle = false,
	},
	{
		type = "recipe",
		name = "improvised-landfill",
		icon = "__TS_Pelagos_CF__/graphics/improvised-landfill.png",
		energy_required = 0.5,
		enabled = false,
		auto_recycle = false,
		category = "organic",
		order = "a[organic-products]-c[improvised-landfill]",
		ingredients = {
			{ type = "item", name = "stone", amount = 20 },
			{ type = "item", name = "spoilage", amount = 60 },
		},
		results = { { type = "item", name = "landfill", amount = 1 } },
		crafting_machine_tint = {
			primary = { r = 0.37, g = 0.37, b = 0.18, a = 1.000 },
			secondary = { r = 0.47, g = 0.47, b = 0.28, a = 1.000 },
			tertiary = { r = 0.37, g = 0.37, b = 0.18, a = 1.000 },
			quaternary = { r = 0.47, g = 0.47, b = 0.28, a = 1.000 },
		},
	},
	--	{
	--		type = "recipe",
	--		name = "calcite-concrete",
	--		icons = {
	--			{ icon = "__base__/graphics/icons/concrete.png", icon_size = 64 },
	--			{ icon = "__space-age__/graphics/icons/calcite.png", icon_size = 64, scale = 0.3, shift = { 8, 8 } },
	--		},
	--		energy_required = 10,
	--		enabled = false,
	--		category = "crafting-with-fluid",
	--		ingredients = {
	--			{ type = "item", name = "calcite", amount = 8 },
	--			{ type = "item", name = "iron-ore", amount = 2 },
	--			{ type = "fluid", name = "water", amount = 100 },
	--		},
	--		results = { { type = "item", name = "concrete", amount = 20 } },
	--		auto_recycle = false,
	--		allow_productivity = true,
	--	},
	{
		type = "recipe",
		name = "cococoncrete",
		icons = {
			{ icon = "__base__/graphics/icons/concrete.png", icon_size = 64 },
			{ icon = "__TS_Pelagos_CF__/graphics/coconut-husk.png", icon_size = 64, scale = 0.3, shift = { 8, 8 } },
		},
		energy_required = 10,
		enabled = false,
		category = "crafting-with-fluid",
		ingredients = {
			{ type = "item", name = "coconut-husk", amount = 10 },
			{ type = "item", name = "iron-ore", amount = 1 },
			{ type = "fluid", name = "water", amount = 100 },
		},
		results = { { type = "item", name = "concrete", amount = 10 } },
		auto_recycle = false,
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "pelagos-spoilage-concrete",
		icons = {
			{ icon = "__base__/graphics/icons/concrete.png", icon_size = 64 },
			{ icon = "__space-age__/graphics/icons/spoilage.png", icon_size = 64, scale = 0.3, shift = { 8, 8 } },
		},
		energy_required = 10,
		enabled = false,
		category = "organic",
		ingredients = {
			{ type = "item", name = "spoilage", amount = 50 },
			{ type = "item", name = "iron-ore", amount = 1 },
			{ type = "fluid", name = "water", amount = 100 },
		},
		results = { { type = "item", name = "concrete", amount = 10 } },
		auto_recycle = false,
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "pelagos-explosives",
		category = "organic",
		icon = "__TS_Pelagos_CF__/graphics/methane-explosives.png",
		ingredients = {
			{ type = "fluid", name = "methane", amount = 50 },
			{ type = "fluid", name = "water", amount = 10 },
		},
		results = { { type = "item", name = "explosives", amount = 2 } },
		allow_productivity = true,
		auto_recycle = false,
		enabled = false,
		crafting_machine_tint = {
			primary = { r = 1.0, g = 0.33, b = 0.15, a = 1.000 },
			secondary = { r = 0.64, g = 0.11, b = 0.3, a = 1.000 },
			tertiary = { r = 1.0, g = 0.33, b = 0.15, a = 1.000 },
			quaternary = { r = 0.64, g = 0.11, b = 0.3, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "nutrients-from-spoilage-methane",
		icons = {
			{ icon = "__TS_Pelagos_CF__/graphics/methane.png", icon_size = 64 },
			{ icon = "__space-age__/graphics/icons/nutrients-from-spoilage.png", icon_size = 64 },
		},
		category = "organic",
		subgroup = "agriculture-processes",
		order = "c[nutrients]-c[nutrients-from-spoilage-methane]",
		enabled = false,
		allow_productivity = true,
		energy_required = 2,
		ingredients = {
			{ type = "item", name = "spoilage", amount = 10 },
			{ type = "fluid", name = "methane", amount = 10 },
		},
		results = { { type = "item", name = "nutrients", amount = 2, percent_spoiled = 0.6 } },
		crafting_machine_tint = {
			primary = { r = 0.8, g = 0.9, b = 1, a = 1.000 },
			secondary = { r = 0.5, g = 0.5, b = 0.8, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "nutrients-spoiling",
		icons = {
			{ icon = "__TS_Pelagos_CF__/graphics/nutrients-spoiling.png", icon_size = 64 },
		},
		category = "organic",
		subgroup = "agriculture-processes",
		order = "c[nutrients]-a[zspoilage]",
		enabled = false,
		allow_productivity = false,
		energy_required = 0.1,
		ingredients = {
			{ type = "item", name = "nutrients", amount = 10 },
		},
		results = { { type = "item", name = "spoilage", amount = 20 } },
		crafting_machine_tint = {
			primary = { r = 0.0, g = 0.1, b = 0, a = 1.000 },
			secondary = { r = 0.0, g = 0.1, b = 0.0, a = 1.000 },
		},
	},
})
