data:extend({
	{
		type = "recipe",
		name = "nutrients-from-coconut-meat",
		icon = "__TS_Pelagos_CF__/graphics/nutrients-from-coconut-meat.png",
		category = "organic",
		subgroup = "agriculture-processes",
		enabled = false,
		allow_productivity = true,
		order = "c[nutrients]-d[nutrients-from-coconut-meat]",
		energy_required = 4,
		ingredients = { { type = "item", name = "coconut-meat", amount = 2 } },
		--results = { { type = "item", name = "nutrients", amount = 8 } },
		results = { { type = "item", name = "nutrients", amount = 10 } },
		crafting_machine_tint = {
			primary = { r = 1.000, g = 1.000, b = 0.900, a = 1.000 },
			secondary = { r = 0.900, g = 0.900, b = 0.800, a = 1.000 },
			tertiary = { r = 1.000, g = 1.000, b = 0.900, a = 1.000 },
			quaternary = { r = 0.900, g = 0.900, b = 0.800, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "coconut-processing",
		icon = "__TS_Pelagos_CF__/graphics/coconut-processing.png",
		category = "organic-or-hand-crafting",
		subgroup = "agriculture-processes",
		order = "a[seeds]-a[coconut-processing]",
		enabled = false,
		allow_productivity = true,
		energy_required = 1,
		ingredients = { { type = "item", name = "coconut", amount = 1 } },
		results = {
			{ type = "item", name = "coconut-seed", amount = 1, probability = 0.09 },
			{ type = "item", name = "coconut-meat", amount = 2 },
			{ type = "item", name = "coconut-husk", amount = 2 },
		},
		crafting_machine_tint = {
			primary = { r = 0.860, g = 0.770, b = 0.590, a = 1.000 },
			secondary = { r = 0.720, g = 0.520, b = 0.260, a = 1.000 },
			tertiary = { r = 0.860, g = 0.770, b = 0.590, a = 1.000 },
			quaternary = { r = 0.720, g = 0.520, b = 0.260, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "coconut-oil",
		category = "organic-or-chemistry",
		additional_categories = { "cryogenics" },
		subgroup = "fluid-recipes",
		order = "a[fluid]-b[coconut-oil]",
		auto_recycle = false,
		energy_required = 6,
		ingredients = {
			{ type = "item", name = "coconut-meat", amount = 10 },
		},
		results = { { type = "fluid", name = "coconut-oil", amount = 10 } },
		allow_productivity = true,
		enabled = false,
		crafting_machine_tint = {
			primary = { r = 1.000, g = 0.940, b = 0.620, a = 1.000 },
			secondary = { r = 0.900, g = 0.780, b = 0.500, a = 1.000 },
			tertiary = { r = 1.000, g = 0.940, b = 0.620, a = 1.000 },
			quaternary = { r = 0.900, g = 0.780, b = 0.500, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "coconut-sealant",
		category = "organic-or-assembling",
		subgroup = "agriculture-processes",
		order = "a[advanced-intermediats]-b[coconut-sealant]",
		auto_recycle = false,
		energy_required = 8,
		ingredients = {
			{ type = "fluid", name = "coconut-oil", amount = 10 },
			{ type = "item", name = "coconut-husk", amount = 5 },
		},
		results = { { type = "item", name = "coconut-sealant", amount = 1 } },
		allow_productivity = true,
		enabled = false,
		crafting_machine_tint = {
			primary = { r = 0.850, g = 0.650, b = 0.450, a = 1.000 },
			secondary = { r = 0.600, g = 0.450, b = 0.300, a = 1.000 },
			tertiary = { r = 0.850, g = 0.650, b = 0.450, a = 1.000 },
			quaternary = { r = 0.600, g = 0.450, b = 0.300, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "pelagos-science-pack",
		category = "organic",
		subgroup = "science-pack",
		surface_conditions = {
			{
				property = "pressure",
				min = 1809,
				max = 1809,
			},
		},
		enabled = false,
		ingredients = {
			{ type = "item", name = "coconut-sealant", amount = 2 },
			{ type = "item", name = "engine-unit", amount = 1 },
			{ type = "item", name = "fermentation-bacteria", amount = 3 },
			{ type = "item", name = "activated-carbon", amount = 1 },
			{ type = "item", name = "titanium-dust", amount = 1 },
		},
		energy_required = 8,
		results = { { type = "item", name = "pelagos-science-pack", amount = 2 } },
		allow_productivity = true,
		crafting_machine_tint = {
			primary = { r = 0.39, g = 0.48, b = 0.26, a = 1.000 },
			secondary = { r = 0.49, g = 0.58, b = 0.36, a = 1.000 },
			tertiary = { r = 0.39, g = 0.48, b = 0.26, a = 1.000 },
			quaternary = { r = 0.49, g = 0.58, b = 0.36, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "fermentation-bacteria",
		category = "organic",
		surface_conditions = {
			{
				property = "pressure",
				min = 0,
				max = 1809,
			},
		},
		subgroup = "agriculture-processes",
		order = "b[agriculture]-d[bacteria]-a[fermentation-bacteria]",
		enabled = false,
		allow_productivity = true,
		energy_required = 1,
		ingredients = {
			{ type = "item", name = "raw-fish", amount = 2 },
			{ type = "fluid", name = "coconut-oil", amount = 30 },
			{ type = "fluid", name = "methane", amount = 100 },
		},
		results = {
			{ type = "item", name = "fermentation-bacteria", amount = 1, probability = 0.1 },
			{ type = "item", name = "spoilage", amount = 5 },
		},
		main_product = "fermentation-bacteria",
		crafting_machine_tint = {
			primary = { r = 0.57, g = 0.72, b = 0.41, a = 1.000 },
			secondary = { r = 0.67, g = 0.82, b = 0.51, a = 1.000 },
			tertiary = { r = 0.57, g = 0.72, b = 0.41, a = 1.000 },
			quaternary = { r = 0.67, g = 0.82, b = 0.51, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "fermentation-bacteria-cultivation",
		icons = {
			{ icon = "__TS_Pelagos_CF__/graphics/fermentation-bacteria-cultivation.png", icon_size = 64 },
			{ icon = "__base__/graphics/icons/fish.png", icon_size = 64, scale = 0.3, shift = { 8, 8 } },
		},
		category = "organic",
		surface_conditions = {
			{
				property = "pressure",
				min = 0,
				max = 1809,
			},
		},
		subgroup = "agriculture-processes",
		order = "b[agriculture]-d[bacteria]-b[fermentation-bacteria-cultivation]",
		enabled = false,
		allow_productivity = true,
		reset_freshness_on_craft = true,
		energy_required = 4,
		ingredients = {
			{ type = "item", name = "fermentation-bacteria", amount = 1 },
			{ type = "item", name = "raw-fish", amount = 1 },
		},
		results = {
			{ type = "item", name = "fermentation-bacteria", amount = 12 },
		},
		crafting_machine_tint = {
			primary = { r = 0.57, g = 0.72, b = 0.41, a = 1.000 },
			secondary = { r = 0.67, g = 0.82, b = 0.51, a = 1.000 },
			tertiary = { r = 0.57, g = 0.72, b = 0.41, a = 1.000 },
			quaternary = { r = 0.67, g = 0.82, b = 0.51, a = 1.000 },
		},
		show_amount_in_title = false,
	},
	{
		type = "recipe",
		name = "fermentation-bacteria-cultivation-fermented-fish",
		icons = {
			{ icon = "__TS_Pelagos_CF__/graphics/fermentation-bacteria-cultivation.png", icon_size = 64 },
			{ icon = "__TS_Pelagos_CF__/graphics/fermented-fish.png", icon_size = 64, scale = 0.3, shift = { 8, 8 } },
		},
		category = "organic",
		surface_conditions = {},
		subgroup = "agriculture-processes",
		order = "b[agriculture]-d[bacteria]-b[fermentation-bacteria-cultivation]",
		enabled = false,
		allow_productivity = true,
		reset_freshness_on_craft = true,
		energy_required = 4,
		ingredients = {
			{ type = "item", name = "fermentation-bacteria", amount = 1 },
			{ type = "item", name = "fermented-fish", amount = 1 },
		},
		results = {
			{ type = "item", name = "fermentation-bacteria", amount = 12 },
		},
		crafting_machine_tint = {
			primary = { r = 0.57, g = 0.72, b = 0.41, a = 1.000 },
			secondary = { r = 0.67, g = 0.82, b = 0.51, a = 1.000 },
			tertiary = { r = 0.57, g = 0.72, b = 0.41, a = 1.000 },
			quaternary = { r = 0.67, g = 0.82, b = 0.51, a = 1.000 },
		},
		show_amount_in_title = false,
	},
	{
		type = "recipe",
		name = "pelagos-biodiesel-tree",
		category = "oil-processing",
		subgroup = "fluid-recipes",
		additional_categories = { "organic" },
		icons = {
			{ icon = "__TS_Pelagos_CF__/graphics/biodiesel.png", icon_size = 64 },
			{ icon = "__space-age__/graphics/icons/tree-seed.png", icon_size = 64, scale = 0.25, shift = { 8, 8 } },
		},
		surface_conditions = {},
		enabled = false,
		allow_productivity = true,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "tree-seed", amount = 5 },
			{ type = "fluid", name = "steam", amount = 50 },
		},
		results = {
			{ type = "fluid", name = "biodiesel", amount = 50 },
		},
		crafting_machine_tint = {
			primary = { r = 0.54, g = 0.45, b = 0.05 },
			secondary = { r = 0.64, g = 0.55, b = 0.15 },
			tertiary = { r = 0.54, g = 0.45, b = 0.05 },
			quaternary = { r = 0.64, g = 0.55, b = 0.15 },
		},
		show_amount_in_title = false,
	},
	{
		type = "recipe",
		name = "pelagos-biodiesel-spoilage",
		category = "organic",
		icons = {
			{ icon = "__TS_Pelagos_CF__/graphics/biodiesel.png", icon_size = 64 },
			{ icon = "__space-age__/graphics/icons/spoilage.png", icon_size = 64, scale = 0.25, shift = { 8, 8 } },
		},
		subgroup = "fluid-recipes",
		surface_conditions = {},
		enabled = false,
		allow_productivity = true,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "spoilage", amount = 40 },
			{ type = "fluid", name = "lubricant", amount = 10 },
		},
		results = {
			{ type = "fluid", name = "biodiesel", amount = 20 },
		},
		crafting_machine_tint = {
			primary = { r = 0.54, g = 0.45, b = 0.05 },
			secondary = { r = 0.64, g = 0.55, b = 0.15 },
			tertiary = { r = 0.54, g = 0.45, b = 0.05 },
			quaternary = { r = 0.64, g = 0.55, b = 0.15 },
		},
		show_amount_in_title = false,
	},
	{
		type = "recipe",
		name = "pelagos-biodiesel-solid-fuel",
		icons = {
			{ icon = "__base__/graphics/icons/solid-fuel.png", icon_size = 64 },
			{ icon = "__TS_Pelagos_CF__/graphics/biodiesel.png", icon_size = 64, scale = 0.3, shift = { -8, -8 } },
		},
		energy_required = 2,
		enabled = false,
		category = "organic-or-chemistry",
		auto_recycle = false,
		subgroup = "fluid-recipes",
		order = "b[fluid-chemistry]-b[solid-fuel-from-biodiesel]",
		ingredients = {
			{ type = "fluid", name = "biodiesel", amount = 15 },
		},
		results = { { type = "item", name = "solid-fuel", amount = 1 } },
		allow_productivity = true,
		crafting_machine_tint = {
			primary = { r = 0.54, g = 0.45, b = 0.05 },
			secondary = { r = 0.64, g = 0.55, b = 0.15 },
			tertiary = { r = 0.54, g = 0.45, b = 0.05 },
			quaternary = { r = 0.64, g = 0.55, b = 0.15 },
		},
	},
	{
		type = "recipe",
		name = "ethanol",
		category = "organic",
		subgroup = "fluid-recipes",
		surface_conditions = {
			{
				property = "pressure",
				min = 1809,
				max = 1809,
			},
		},
		enabled = false,
		allow_productivity = true,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "fermentation-bacteria", amount = 5 },
			{ type = "item", name = "nutrients", amount = 20 },
			{ type = "fluid", name = "water", amount = 100 },
			{ type = "item", name = "activated-carbon", amount = 3 },
		},
		results = {
			{ type = "fluid", name = "ethanol", amount = 120 },
		},
		crafting_machine_tint = {
			primary = { r = 0.68, g = 0.83, b = 0.9, a = 1.000 },
			secondary = { r = 0.78, g = 0.93, b = 1.0, a = 1.000 },
			tertiary = { r = 0.68, g = 0.83, b = 0.9, a = 1.000 },
			quaternary = { r = 0.78, g = 0.93, b = 1.0, a = 1.000 },
		},
		show_amount_in_title = false,
	},
	{
		type = "recipe",
		name = "degradation-module",
		enabled = false,
		category = "electronics",
		ingredients = {
			{ type = "item", name = "electronic-circuit", amount = 5 },
			{ type = "item", name = "advanced-circuit", amount = 5 },
		},
		energy_required = 15,
		results = { { type = "item", name = "degradation-module", amount = 1 } },
	},
	{
		type = "recipe",
		name = "degradation-module-2",
		enabled = false,
		category = "electronics",
		ingredients = {
			{ type = "item", name = "degradation-module", amount = 4 },
			{ type = "item", name = "advanced-circuit", amount = 5 },
			{ type = "item", name = "processing-unit", amount = 5 },
		},
		energy_required = 30,
		results = { { type = "item", name = "degradation-module-2", amount = 1 } },
	},
	{
		type = "recipe",
		name = "degradation-module-3",
		enabled = false,
		auto_recycle = false,
		category = "electronics",
		ingredients = {
			{ type = "item", name = "degradation-module-2", amount = 4 },
			{ type = "item", name = "advanced-circuit", amount = 5 },
			{ type = "item", name = "processing-unit", amount = 5 },
			{ type = "item", name = "fermentation-bacteria", amount = 5 },
		},
		energy_required = 60,
		results = { { type = "item", name = "degradation-module-3", amount = 1 } },
	},
	{
		type = "recipe",
		name = "wood-spoiling",
		icon = "__TS_Pelagos_CF__/graphics/rotting-wood.png",
		category = "organic",
		subgroup = "agriculture-products",
		order = "a[seeds]-c[wood-spoiling]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 6,
		ingredients = {
			{ type = "item", name = "wood", amount = 5 },
		},
		results = {
			{ type = "item", name = "spoilage", amount = 40 },
		},
		crafting_machine_tint = {
			primary = { r = 0.27, g = 0.27, b = 0.08, a = 1.000 },
			secondary = { r = 0.37, g = 0.37, b = 0.18, a = 1.000 },
			tertiary = { r = 0.27, g = 0.27, b = 0.08, a = 1.000 },
			quaternary = { r = 0.37, g = 0.37, b = 0.18, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "coconut-husk-spoiling",
		icon = "__TS_Pelagos_CF__/graphics/coconut-husk-spoiling.png",
		category = "organic",
		subgroup = "agriculture-products",
		order = "a[seeds]-c[wood-spoiling]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 6,
		ingredients = {
			{ type = "item", name = "coconut-husk", amount = 5 },
		},
		results = {
			{ type = "item", name = "spoilage", amount = 20 },
		},
		crafting_machine_tint = {
			primary = { r = 0.27, g = 0.27, b = 0.08, a = 1.000 },
			secondary = { r = 0.37, g = 0.37, b = 0.18, a = 1.000 },
			tertiary = { r = 0.27, g = 0.27, b = 0.08, a = 1.000 },
			quaternary = { r = 0.37, g = 0.37, b = 0.18, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "lighthouse",
		category = "advanced-crafting",
		surface_conditions = {
			{
				property = "pressure",
				min = 1809,
				max = 1809,
			},
		},
		enabled = false,
		ingredients = {
			{ type = "item", name = "pipe", amount = 10 },
			{ type = "item", name = "iron-plate", amount = 20 },
			{ type = "item", name = "concrete", amount = 200 },
			{ type = "item", name = "coconut-sealant", amount = 10 },
		},
		energy_required = 10,
		results = { { type = "item", name = "lighthouse", amount = 1 } },
	},
	{
		type = "recipe",
		name = "diesel-mining-drill",
		energy_required = 2,
		ingredients = {
			{ type = "item", name = "iron-plate", amount = 10 },
			{ type = "item", name = "iron-gear-wheel", amount = 5 },
			{ type = "item", name = "engine-unit", amount = 2 },
			{ type = "item", name = "coconut-sealant", amount = 6 },
		},
		results = { { type = "item", name = "diesel-mining-drill", amount = 1 } },
		enabled = false,
	},
	{

		type = "recipe",
		name = "diesel-inserter",
		enabled = false,
		ingredients = {
			{ type = "item", name = "pipe", amount = 4 },
			{ type = "item", name = "engine-unit", amount = 2 },
			{ type = "item", name = "coconut-sealant", amount = 4 },
			{ type = "item", name = "burner-inserter", amount = 1 },
		},
		results = { { type = "item", name = "diesel-inserter", amount = 1 } },
	},
	{

		type = "recipe",
		name = "fast-diesel-inserter",
		enabled = false,
		ingredients = {
			{ type = "item", name = "pipe", amount = 4 },
			{ type = "item", name = "engine-unit", amount = 1 },
			{ type = "item", name = "coconut-sealant", amount = 4 },
			{ type = "item", name = "burner-inserter", amount = 1 },
		},
		results = { { type = "item", name = "fast-diesel-inserter", amount = 1 } },
	},
	{

		type = "recipe",
		name = "long-handed-diesel-inserter",
		enabled = false,
		ingredients = {
			{ type = "item", name = "pipe", amount = 4 },
			{ type = "item", name = "engine-unit", amount = 1 },
			{ type = "item", name = "coconut-sealant", amount = 4 },
			{ type = "item", name = "burner-inserter", amount = 1 },
		},
		results = { { type = "item", name = "long-handed-diesel-inserter", amount = 1 } },
	},
	{

		type = "recipe",
		name = "crane-bulk-diesel-inserter",
		enabled = false,
		ingredients = {
			{ type = "item", name = "pipe", amount = 4 },
			{ type = "item", name = "engine-unit", amount = 5 },
			{ type = "item", name = "coconut-sealant", amount = 6 },
			{ type = "item", name = "burner-inserter", amount = 1 },
			{ type = "item", name = "iron-plate", amount = 10 },
			{ type = "item", name = "titanium-plate", amount = 5 },
		},
		results = { { type = "item", name = "crane-bulk-diesel-inserter", amount = 1 } },
	},
	{

		type = "recipe",
		name = "crane-stack-diesel-inserter",
		enabled = false,
		ingredients = {
			{ type = "item", name = "engine-unit", amount = 5 },
			{ type = "item", name = "coconut-sealant", amount = 6 },
			{ type = "item", name = "stack-inserter", amount = 1 },
			{ type = "item", name = "crane-bulk-diesel-inserter", amount = 1 },
			{ type = "item", name = "titanium-plate", amount = 10 },
		},
		results = { { type = "item", name = "crane-stack-diesel-inserter", amount = 1 } },
	},
	{
		type = "recipe",
		name = "diesel-assembling-machine",
		enabled = false,
		ingredients = {
			{ type = "item", name = "steel-plate", amount = 5 },
			{ type = "item", name = "coconut-sealant", amount = 10 },
			{ type = "item", name = "iron-plate", amount = 15 },
			{ type = "item", name = "iron-gear-wheel", amount = 7 },
			{ type = "item", name = "engine-unit", amount = 1 },
		},
		results = { { type = "item", name = "diesel-assembling-machine", amount = 1 } },
	},
	{
		type = "recipe",
		name = "diesel-pump",
		enabled = false,
		ingredients = {
			{ type = "item", name = "engine-unit", amount = 2 },
			{ type = "item", name = "pipe", amount = 4 },
			{ type = "item", name = "coconut-sealant", amount = 2 },
		},
		results = { { type = "item", name = "diesel-pump", amount = 1 } },
	},
	{
		type = "recipe",
		name = "diesel-agricultural-tower",
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "coconut-sealant", amount = 2 },
			{ type = "item", name = "steel-plate", amount = 10 },
			{ type = "item", name = "engine-unit", amount = 3 },
			{ type = "item", name = "spoilage", amount = 20 },
			{ type = "item", name = "landfill", amount = 1 },
		},
		results = { { type = "item", name = "diesel-agricultural-tower", amount = 1 } },
		enabled = false,
	},
	{
		type = "recipe",
		name = "pelagos-casting-engine-unit",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "b[casting]-h[casting-engine-unit]",
		icon = "__TS_Pelagos_CF__/graphics/casting-engine-unit.png",
		enabled = false,
		ingredients = {
			{ type = "fluid", name = "molten-iron", amount = 50, fluidbox_multiplier = 50 },
			{ type = "item", name = "activated-carbon", amount = 3 },
		},
		energy_required = 10,
		-- energy_required = 10, for assembling machine
		allow_decomposition = false,
		results = { { type = "item", name = "engine-unit", amount = 1 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "titanium-dust",
		category = "organic",
		subgroup = "agriculture-products",
		--order = "a[seeds]-c[]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 5,
		ingredients = {
			{ type = "fluid", name = "titanium-sludge", amount = 50 },
			{ type = "item", name = "fermentation-bacteria", amount = 1 },
		},
		results = {
			{ type = "item", name = "titanium-dust", amount = 1, probability = 0.25 },
			{ type = "item", name = "spoilage", amount = 8 },
		},
		crafting_machine_tint = {
			primary = { r = 0.45, g = 0.67, b = 0.72, a = 1.000 },
			secondary = { r = 0.65, g = 0.87, b = 0.92, a = 1.000 },
			tertiary = { r = 0.45, g = 0.67, b = 0.72, a = 1.000 },
			quaternary = { r = 0.65, g = 0.87, b = 0.92, a = 1.000 },
		},
		main_product = "titanium-dust",
	},
	{
		type = "recipe",
		name = "advanced-titanium-plate-from-dust",
		icon = "__TS_Pelagos_CF__/graphics/titanium/advanced-titanium-plate-from-dust.png",
		--subgroup = "agriculture-products",
		--order = "a[seeds]-c[]",
		auto_recycle = false,
		category = "smelting",
		enabled = false,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "titanium-dust", amount = 1 },
			{ type = "item", name = "activated-carbon", amount = 10 },
		},
		results = { { type = "item", name = "titanium-plate", amount = 1 } },
		allow_productivity = true,
		crafting_machine_tint = {
			primary = { r = 0.45, g = 0.67, b = 0.72, a = 1.000 },
			secondary = { r = 0.65, g = 0.87, b = 0.92, a = 1.000 },
			tertiary = { r = 0.45, g = 0.67, b = 0.72, a = 1.000 },
			quaternary = { r = 0.65, g = 0.87, b = 0.92, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "titanium-plate-from-dust",
		icon = "__TS_Pelagos_CF__/graphics/titanium/titanium-plate-from-dust.png",
		--subgroup = "agriculture-products",
		--order = "a[seeds]-c[]",
		auto_recycle = false,
		category = "smelting",
		enabled = false,
		energy_required = 10,
		ingredients = { { type = "item", name = "titanium-dust", amount = 2 } },
		results = { { type = "item", name = "titanium-plate", amount = 1 } },
		allow_productivity = true,
		crafting_machine_tint = {
			primary = { r = 0.45, g = 0.67, b = 0.72, a = 1.000 },
			secondary = { r = 0.65, g = 0.87, b = 0.92, a = 1.000 },
			tertiary = { r = 0.45, g = 0.67, b = 0.72, a = 1.000 },
			quaternary = { r = 0.65, g = 0.87, b = 0.92, a = 1.000 },
		},
	},

	{
		type = "recipe",
		name = "titanium-barrel",
		category = "crafting",
		energy_required = 1,
		subgroup = "intermediate-product",
		enabled = false,
		ingredients = {
			{ type = "item", name = "titanium-plate", amount = 1 },
		},
		results = { { type = "item", name = "titanium-barrel", amount = 1 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "diesel-dragon",
		enabled = false,
		ingredients = {
			{ type = "item", name = "titanium-plate", amount = 500 },
			{ type = "item", name = "steel-plate", amount = 1000 },
			{ type = "item", name = "concrete", amount = 1000 },
			{ type = "item", name = "pipe", amount = 300 },
			{ type = "item", name = "processing-unit", amount = 200 },
			{ type = "item", name = "engine-unit", amount = 400 },
		},
		energy_required = 30,
		results = { { type = "item", name = "diesel-dragon", amount = 1 } },
		requester_paste_multiplier = 1,
	},
})

data:extend({
	{
		type = "recipe",
		name = "copper-biter-egg",
		category = "captive-spawner-process",
		order = "c[eggs]-a[copper-biter-egg]",
		hide_from_player_crafting = true,
		auto_recycle = false,
		preserve_products_in_machine_output = true,
		energy_required = 10,
		ingredients = {},
		results = {
			{ type = "item", name = "copper-biter-egg", amount = 10 },
		},
		enabled = false,
	},
	{
		type = "recipe",
		name = "copper-plate-from-copper-biter-egg",
		icon = "__TS_Pelagos_CF__/graphics/copper-plate.png",
		category = "smelting",
		auto_recycle = false,
		energy_required = 3.2,
		ingredients = { { type = "item", name = "copper-biter-egg", amount = 1 } },
		results = { { type = "item", name = "copper-plate", amount = 1 } },
		allow_productivity = true,
		enabled = false,
	},
	{
		type = "recipe",
		name = "copper-ore-bitter-egg",
		category = "organic",
		subgroup = "agriculture-products",
		order = "a[pelagos]-c[copper-ore-bitter-egg]",
		icon = "__TS_Pelagos_CF__/graphics/copper-ore.png",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "copper-biter-egg", amount = 5 },
			{ type = "item", name = "calcite", amount = 1 },
			{ type = "fluid", name = "ethanol", amount = 25 },
		},
		results = {
			{ type = "item", name = "copper-ore", amount = 5 },
		},
		crafting_machine_tint = {
			primary = { r = 0.7, g = 0.3, b = 0.18, a = 1.000 },
			secondary = { r = 0.87, g = 0.41, b = 0.25, a = 1.000 },
			tertiary = { r = 0.7, g = 0.3, b = 0.18, a = 1.000 },
			quaternary = { r = 0.87, g = 0.41, b = 0.25, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "captive-copper-biter-spawner",
		category = "cryogenics",
		energy_required = 10,
		enabled = false,
		reset_freshness_on_craft = true,
		ingredients = {
			{ type = "item", name = "copper-biter-egg", amount = 10 },
			{ type = "item", name = "pelagos-capture-robot-rocket", amount = 1 },
			{ type = "fluid", name = "ethanol", amount = 500 },
			{ type = "fluid", name = "fluoroketone-cold", amount = 100 },
		},
		results = { { type = "item", name = "captive-copper-biter-spawner", amount = 1 } },
	},
})
data:extend({
	{
		type = "recipe",
		name = "fermented-fish",
		category = "organic",
		subgroup = "agriculture-products",
		order = "a[seeds]-c[wood-spoiling]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "coconut-meat", amount = 5 },
			{ type = "item", name = "raw-fish", amount = 10 },
			{ type = "item", name = "fermentation-bacteria", amount = 5 },
		},
		results = {
			--{ type = "item", name = "fermented-fish", amount = 5 },
			{ type = "item", name = "fermented-fish", amount = 10 },
		},
		crafting_machine_tint = {
			primary = { r = 0.6, g = 0.77, b = 0.82, a = 1.000 },
			secondary = { r = 0.78, g = 0.82, b = 0.35, a = 1.000 },
			tertiary = { r = 0.6, g = 0.77, b = 0.82, a = 1.000 },
			quaternary = { r = 0.78, g = 0.82, b = 0.35, a = 1.000 },
		},
	},
})
--weapons
data:extend({
	{
		type = "recipe",
		name = "poison-rocket",
		enabled = false,
		energy_required = 4,
		ingredients = {
			{ type = "item", name = "iron-plate", amount = 1 },
			{ type = "item", name = "poison-capsule", amount = 1 },
			{ type = "item", name = "coconut-sealant", amount = 1 },
			{ type = "item", name = "explosives", amount = 1 },
		},
		results = { { type = "item", name = "poison-rocket", amount = 1 } },
	},
	{
		type = "recipe",
		name = "slowdown-rocket",
		enabled = false,
		energy_required = 4,
		ingredients = {
			{ type = "item", name = "iron-plate", amount = 1 },
			{ type = "item", name = "slowdown-capsule", amount = 1 },
			{ type = "item", name = "coconut-sealant", amount = 1 },
			{ type = "item", name = "explosives", amount = 1 },
		},
		results = { { type = "item", name = "slowdown-rocket", amount = 1 } },
	},
	{
		type = "recipe",
		name = "pelagos-capture-robot-rocket",
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "titanium-plate", amount = 3 },
			{ type = "item", name = "fermented-fish", amount = 10 },
			{ type = "item", name = "engine-unit", amount = 5 },
			{ type = "item", name = "plastic-bar", amount = 10 },
		},
		results = { { type = "item", name = "pelagos-capture-robot-rocket", amount = 1 } },
		enabled = false,
		auto_recycle = false,
	},
	{
		type = "recipe",
		name = "corrosive-firearm-magazine",
		energy_required = 1,
		ingredients = {
			{ type = "item", name = "firearm-magazine", amount = 6 },
			{ type = "item", name = "fermentation-bacteria", amount = 1 },
		},
		results = { { type = "item", name = "corrosive-firearm-magazine", amount = 6 } },
		enabled = false,
		auto_recycle = false,
	},
	{
		type = "recipe",
		name = "heavy-gun-turret",
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "titanium-plate", amount = 10 },
			{ type = "item", name = "iron-gear-wheel", amount = 20 },
			{ type = "item", name = "steel-plate", amount = 30 },
			{ type = "item", name = "engine-unit", amount = 10 },
			{ type = "item", name = "plastic-bar", amount = 15 },
		},
		results = { { type = "item", name = "heavy-gun-turret", amount = 1 } },
		enabled = false,
		--auto_recycle = false,
	},
	{
		type = "recipe",
		name = "portable-diesel-generator",
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "titanium-plate", amount = 100 },
			{ type = "item", name = "iron-gear-wheel", amount = 60 },
			{ type = "item", name = "pipe", amount = 50 },
			{ type = "item", name = "engine-unit", amount = 150 },
			{ type = "item", name = "plastic-bar", amount = 30 },
			{ type = "item", name = "coconut-sealant", amount = 50 },
		},
		results = { { type = "item", name = "portable-diesel-generator", amount = 1 } },
		enabled = false,
		--auto_recycle = false,
	},
})

data:extend({
	{
		type = "recipe",
		name = "metallic-asteroid-methane-crushing",
		icon = "__TS_Pelagos_CF__/graphics/metallic-asteroid-methane-crushing.png",
		category = "organic-or-chemistry",
		subgroup = "space-crushing",
		order = "g-a-a",
		auto_recycle = false,
		enabled = false,
		ingredients = {
			{ type = "item", name = "metallic-asteroid-chunk", amount = 1 },
			{ type = "fluid", name = "methane", amount = 20 },
		},
		energy_required = 2,
		results = {
			{ type = "item", name = "iron-ore", amount = 40 },
		},
		crafting_machine_tint = {
			primary = { r = 79, g = 121, b = 148, a = 1.000 },
			secondary = { r = 85, g = 132, b = 161, a = 1.000 },
			tertiary = { r = 79, g = 121, b = 148, a = 1.000 },
			quaternary = { r = 85, g = 132, b = 161, a = 1.000 },
		},
		allow_productivity = true,
		allow_decomposition = false,
	},
	{
		type = "recipe",
		name = "carbonic-asteroid-gasification",
		icon = "__TS_Pelagos_CF__/graphics/carbonic-asteroid-gasification.png",
		category = "organic",
		subgroup = "space-crushing",
		order = "g-a-b",
		auto_recycle = false,
		enabled = false,
		ingredients = {
			{ type = "item", name = "carbonic-asteroid-chunk", amount = 1 },
			{ type = "fluid", name = "water", amount = 20 },
		},
		energy_required = 2,
		results = {
			{ type = "fluid", name = "methane", amount = 200 },
		},
		crafting_machine_tint = {
			primary = { r = 163, g = 209, b = 62, a = 1.000 },
			secondary = { r = 193, g = 239, b = 92, a = 1.000 },
			tertiary = { r = 163, g = 209, b = 62, a = 1.000 },
			quaternary = { r = 193, g = 239, b = 92, a = 1.000 },
		},
		allow_productivity = true,
		allow_decomposition = false,
	},
	{
		type = "recipe",
		name = "oxide-asteroid-melting",
		icons = {
			{ icon = "__space-age__/graphics/icons/oxide-asteroid-chunk.png", icon_size = 64 },
			{ icon = "__base__/graphics/icons/fluid/water.png", icon_size = 64, scale = 0.4, shift = { 8, -8 } },
		},
		category = "organic",
		subgroup = "space-crushing",
		order = "g-a-c",
		auto_recycle = false,
		enabled = false,
		ingredients = {
			{ type = "item", name = "oxide-asteroid-chunk", amount = 1 },
			{ type = "item", name = "spoilage", amount = 1 },
		},
		energy_required = 2,
		results = {
			{ type = "fluid", name = "water", amount = 200 },
		},
		crafting_machine_tint = {
			primary = { r = 42, g = 143, b = 189, a = 1.000 },
			secondary = { r = 7, g = 80, b = 98, a = 1.000 },
			tertiary = { r = 42, g = 143, b = 189, a = 1.000 },
			quaternary = { r = 7, g = 80, b = 98, a = 1.000 },
		},
		allow_productivity = true,
		allow_decomposition = false,
	},
})
data:extend({
	{
		type = "recipe",
		name = "stone-erosion",
		category = "organic",
		icons = {
			{ icon = "__base__/graphics/icons/stone.png", icon_size = 64 },
			{ icon = "__base__/graphics/icons/fluid/water.png", icon_size = 64, scale = 0.3, shift = { 8, 8 } },
		},
		enabled = false,
		auto_recycle = false,
		energy_required = 5.0,
		ingredients = {
			{ type = "fluid", name = "water", amount = 10 },
			{ type = "item", name = "stone", amount = 5 },
		},
		main_product = "sand",
		results = {
			{ type = "item", name = "sand", amount = 10 },
			{ type = "fluid", name = "water", amount = 2, ignored_by_stats = 2, ignored_by_productivity = 2 },
		},
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "pelagos-sandfill",
		energy_required = 0.5,
		enabled = false,
		auto_recycle = false,
		category = "organic",
		ingredients = {
			{ type = "item", name = "sand", amount = 45 },
		},
		results = { { type = "item", name = "pelagos-sandfill", amount = 1 } },
	},
})

if mods["lubrication_tower"] then
	data:extend({
		{
			type = "recipe",
			name = "lubrication-tower",
			enabled = false,
			energy_required = 20,
			ingredients = {
				{ type = "item", name = "steel-plate", amount = 50 },
				{ type = "item", name = "titanium-plate", amount = 10 },
				{ type = "item", name = "pipe", amount = 20 },
				{ type = "item", name = "coconut-sealant", amount = 20 },
				{ type = "item", name = "engine-unit", amount = 10 },
				{ type = "item", name = "refined-concrete", amount = 100 },
			},
			results = { { type = "item", name = "lubrication-tower", amount = 1 } },
			surface_conditions = {
				{
					property = "pressure",
					min = 1809,
					max = 1809,
				},
			},
		},
	})
	data.raw.item["lubrication-tower"].default_import_location = "pelagos"
end

if mods["Krastorio2-spaced-out"] then
	local electronic_components = table.deepcopy(data.raw["recipe"]["kr-electronic-components"])
	electronic_components.name = "pelagos-electronic-components"
	electronic_components.icons = {
		{ icon = "__Krastorio2Assets__/icons/items/electronic-components.png", icon_size = 64 },
		{ icon = "__TS_Pelagos_CF__/graphics/pelagos.png", icon_size = 64, scale = 0.25, shift = { 8, 8 } },
	}
	electronic_components.ingredients = {
		{ type = "item", name = "kr-glass", amount = 2 },
		{ type = "item", name = "copper-cable", amount = 4 },
		{ type = "item", name = "coconut-sealant", amount = 2 },
		{ type = "item", name = "plastic-bar", amount = 2 },
	}
	electronic_components.surface_conditions = {
		{
			property = "pressure",
			min = 1809,
			max = 1809,
		},
	}
	data:extend({ electronic_components })
	table.insert(
		data.raw["technology"]["advanced-circuit"].effects,
		{ type = "unlock-recipe", recipe = "pelagos-electronic-components" }
	)
end
